### ISSUE TITLE
Error while executing the command present in the README

### ISSUE THREAD

**Issue by codinglara** [iai-group/UserSimConvRec#3]
>> python3 -m simulation.dialog.conv_man
                                                                                                                                    
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/Desktop/conv_sim/UserSimConvRec/simulation/dialog/conv_man.py", line 210, in <module>
    user = MovieSimulatedUser("data/1224_ms.json", RESPONSE_TEMPLATES_MS, "ms")
  File "/usr/local/Desktop/conv_sim/UserSimConvRec/simulation/user/movies/movies_simulated_user.py", line 77, in __init__
    self.user = UserGenerator.initial(self, num_user=1)[0]
  File "/usr/local/Desktop/conv_sim/UserSimConvRec/simulation/user/user_generator.py", line 134, in initial
    user_all = self.rates(if_title=if_title)
  File "/usr/local/Desktop/conv_sim/UserSimConvRec/simulation/user/user_generator.py", line 108, in rates
    genres = self.__mov.get(movie_id).get("genres")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by venkataraviteja26** [comment]
@codinglara I am getting the same error
